### PR TITLE
Fixed both xxxAmbientToLux

### PR DESCRIPTION
**Pull request by ElFishi**
1. iac can't go negative as per data sheet
2. denominator needs gain factor and not gain register value

### CODE REVIEW

**Comment by depau** [comment]
Thanks for your contribution. Can you confirm you tested it and it works? I don't have time to set up a testing environment.

Thanks

**Comment by debsahu** [comment]
In bright light, channel 1 and 0 give a value of 1024. And the Lux calculated by this is no longer negative, but rather zero. Looking at the datasheet, the calculations done are correct, but shouldn't this the max measurable lux instead of zero?

**Comment by debsahu** [comment]
Also now the lux value measured is drastically small. Increasing the denominator has decreased the lux value.

**Comment by debsahu** [comment]
Shouldn't "DEFAULT_ATIME" be 0xED which is recommended as ALSIT will be 50ms.

**Comment by debsahu** [comment]
I went through the changes, I agree that the implementation by @ElFishi is as per the documentation. But at high light values instead of negative, we get a zero. If the documentation says that, we got to live with it. Please merge! But before merging, change the DEFAULT_ATIME to 0xED so ASIT is 50ms, and DEFAULT_AGAIN to AGAIN_1X. These changes can give a broader range of lux values.

**Comment by depau** [comment]
Thank you very much guys :)

**Pull request merged**
