### PR TITLE
Adapt to compile for ESP8266

### PR DESCRIPTION
**Pull request by unaiur**
Also, define missing register APDS9930_PTIME

### CODE REVIEW

**Comment by depau** [comment]
@unaiur I don't see any useful changes in your commit. Maybe you PRed the wrong ones? I'm not going to merge the change from NA to NOTAVAILABLE, as it may break the API to people who are already using the library as it is  without any actual major changes.

**Comment by depau** [comment]
@unaiur The only change I see is the addition of the PTIME register, for which you're not providing any code anyways. What is that register used for? Would the user like some functions that abstract some of its functionalities? Please submit any changes on a commit by itself.

At the moment I'm not merging this pull request. I'm sorry but as this library is already being used by a bunch of people, I can't blindly merge commits.

Thanks for taking the time to help me improve it anyways, I really appreciate it!

**Comment by unaiur** [comment]
NA is already defined by the WIFI core in ESP8266. Your library isn't
compiling in this platform unless you change this enumeration value.

If you aren't going to rename it, I will create a "portable" version of
your library with just this change.

Best regards.

**Comment by unaiur** [comment]
My fix can be improved, of course, defining new names with the library
prefix and then define macros with the old names only for AVR platform.

**Comment by depau** [comment]
@unaiur Okay. Then you still need to make sure NA is available on Arduino as an alias by using precompiler instructions and specify it's deprecated.

I would have done it but I'm really busy, I'll actually check it thoroughly in a few days ;)

**Comment by depau** [comment]
Okay, I merged it and added the alias. Thank you very much for your help ;)

**Pull request merged**
